08/28/17 13:04:55 49857 Checking cache for jobid 10013540
08/28/17 13:04:55 49857 Starting query to fill cache.
08/28/17 13:04:55 49857 Starting qstat.
08/28/17 13:04:55 49857 1ERROR: Internal exception, No option 'pbs_pro' in section: 'blahp'
08/28/17 13:04:55 49857 Jobid 10013540 not in cache; querying PBS
08/28/17 13:04:55 49857 Starting qstat.
08/28/17 13:05:56 49866 Checking cache for jobid 10013540
08/28/17 13:05:56 49866 Starting query to fill cache.
08/28/17 13:05:56 49866 Starting qstat.
08/28/17 13:05:56 49866 1ERROR: Internal exception, No option 'pbs_pro' in section: 'blahp'
08/28/17 13:05:56 49866 Jobid 10013540 not in cache; querying PBS
08/28/17 13:05:56 49866 Starting qstat.
08/28/17 13:06:56 49875 Checking cache for jobid 10013540
08/28/17 13:06:56 49875 Starting query to fill cache.
08/28/17 13:06:56 49875 Starting qstat.
08/28/17 13:06:56 49875 1ERROR: Internal exception, No option 'pbs_pro' in section: 'blahp'
08/28/17 13:06:56 49875 Jobid 10013540 not in cache; querying PBS
08/28/17 13:06:56 49875 Starting qstat.
08/28/17 14:02:50 50446 Checking cache for jobid 10017805
08/28/17 14:02:50 50446 Starting query to fill cache.
08/28/17 14:02:50 50446 Starting qstat.
08/28/17 14:02:50 50446 1ERROR: Internal exception, No option 'pbs_pro' in section: 'blahp'
08/28/17 14:02:50 50446 Jobid 10017805 not in cache; querying PBS
08/28/17 14:02:50 50446 Starting qstat.
08/28/17 14:03:50 50455 Checking cache for jobid 10017805
08/28/17 14:03:50 50455 Starting query to fill cache.
08/28/17 14:03:50 50455 Starting qstat.
08/28/17 14:03:50 50455 1ERROR: Internal exception, No option 'pbs_pro' in section: 'blahp'
08/28/17 14:03:50 50455 Jobid 10017805 not in cache; querying PBS
08/28/17 14:03:50 50455 Starting qstat.
08/28/17 14:04:50 50460 Checking cache for jobid 10017805
08/28/17 14:04:50 50460 Starting query to fill cache.
08/28/17 14:04:50 50460 Starting qstat.
08/28/17 14:04:50 50460 1ERROR: Internal exception, No option 'pbs_pro' in section: 'blahp'
08/28/17 14:04:50 50460 Jobid 10017805 not in cache; querying PBS
08/28/17 14:04:50 50460 Starting qstat.
08/28/17 14:05:50 50465 Checking cache for jobid 10017805
08/28/17 14:05:50 50465 Starting query to fill cache.
08/28/17 14:05:50 50465 Starting qstat.
08/28/17 14:05:50 50465 1ERROR: Internal exception, No option 'pbs_pro' in section: 'blahp'
08/28/17 14:05:50 50465 Jobid 10017805 not in cache; querying PBS
08/28/17 14:05:50 50465 Starting qstat.
08/28/17 14:06:50 50474 Checking cache for jobid 10017805
08/28/17 14:06:50 50474 Starting query to fill cache.
08/28/17 14:06:50 50474 Starting qstat.
08/28/17 14:06:50 50474 1ERROR: Internal exception, No option 'pbs_pro' in section: 'blahp'
08/28/17 14:06:50 50474 Jobid 10017805 not in cache; querying PBS
08/28/17 14:06:50 50474 Starting qstat.
08/28/17 15:02:47 51009 Checking cache for jobid 10021614
08/28/17 15:02:47 51009 Starting query to fill cache.
08/28/17 15:02:47 51009 Starting qstat.
08/28/17 15:02:47 51009 1ERROR: Internal exception, No option 'pbs_pro' in section: 'blahp'
08/28/17 15:02:47 51009 Jobid 10021614 not in cache; querying PBS
08/28/17 15:02:47 51009 Starting qstat.
08/28/17 15:03:47 51018 Checking cache for jobid 10021614
08/28/17 15:03:47 51018 Starting query to fill cache.
08/28/17 15:03:47 51018 Starting qstat.
08/28/17 15:03:47 51018 1ERROR: Internal exception, No option 'pbs_pro' in section: 'blahp'
08/28/17 15:03:47 51018 Jobid 10021614 not in cache; querying PBS
08/28/17 15:03:47 51018 Starting qstat.
08/28/17 15:04:48 51023 Checking cache for jobid 10021614
08/28/17 15:04:48 51023 Starting query to fill cache.
08/28/17 15:04:48 51023 Starting qstat.
08/28/17 15:04:48 51023 1ERROR: Internal exception, No option 'pbs_pro' in section: 'blahp'
08/28/17 15:04:48 51023 Jobid 10021614 not in cache; querying PBS
08/28/17 15:04:48 51023 Starting qstat.
08/28/17 15:05:49 51028 Checking cache for jobid 10021614
08/28/17 15:05:49 51028 Starting query to fill cache.
08/28/17 15:05:49 51028 Starting qstat.
08/28/17 15:05:49 51028 1ERROR: Internal exception, No option 'pbs_pro' in section: 'blahp'
08/28/17 15:05:49 51028 Jobid 10021614 not in cache; querying PBS
08/28/17 15:05:49 51028 Starting qstat.
08/28/17 15:06:49 51037 Checking cache for jobid 10021614
08/28/17 15:06:49 51037 Starting query to fill cache.
08/28/17 15:06:49 51037 Starting qstat.
08/28/17 15:06:49 51037 1ERROR: Internal exception, No option 'pbs_pro' in section: 'blahp'
08/28/17 15:06:49 51037 Jobid 10021614 not in cache; querying PBS
08/28/17 15:06:49 51037 Starting qstat.
08/28/17 16:02:48 51473 Checking cache for jobid 10026122
08/28/17 16:02:48 51473 Starting query to fill cache.
08/28/17 16:02:48 51473 Starting qstat.
08/28/17 16:02:48 51473 1ERROR: Internal exception, No option 'pbs_pro' in section: 'blahp'
08/28/17 16:02:48 51473 Jobid 10026122 not in cache; querying PBS
08/28/17 16:02:48 51473 Starting qstat.
08/28/17 16:03:48 51478 Checking cache for jobid 10026122
08/28/17 16:03:48 51478 Starting query to fill cache.
08/28/17 16:03:48 51478 Starting qstat.
08/28/17 16:03:48 51478 1ERROR: Internal exception, No option 'pbs_pro' in section: 'blahp'
08/28/17 16:03:48 51478 Jobid 10026122 not in cache; querying PBS
08/28/17 16:03:48 51478 Starting qstat.
08/28/17 16:04:49 51487 Checking cache for jobid 10026122
08/28/17 16:04:49 51487 Starting query to fill cache.
08/28/17 16:04:49 51487 Starting qstat.
08/28/17 16:04:49 51487 1ERROR: Internal exception, No option 'pbs_pro' in section: 'blahp'
08/28/17 16:04:49 51487 Jobid 10026122 not in cache; querying PBS
08/28/17 16:04:49 51487 Starting qstat.
08/28/17 16:05:49 51492 Checking cache for jobid 10026122
08/28/17 16:05:49 51492 Starting query to fill cache.
08/28/17 16:05:49 51492 Starting qstat.
08/28/17 16:05:49 51492 1ERROR: Internal exception, No option 'pbs_pro' in section: 'blahp'
08/28/17 16:05:49 51492 Jobid 10026122 not in cache; querying PBS
08/28/17 16:05:49 51492 Starting qstat.
08/28/17 16:06:49 51501 Checking cache for jobid 10026122
08/28/17 16:06:49 51501 Starting query to fill cache.
08/28/17 16:06:49 51501 Starting qstat.
08/28/17 16:06:49 51501 1ERROR: Internal exception, No option 'pbs_pro' in section: 'blahp'
08/28/17 16:06:49 51501 Jobid 10026122 not in cache; querying PBS
08/28/17 16:06:49 51501 Starting qstat.
10/23/17 11:58:41 164098 Traceback (most recent call last):
  File "/usr/libexec/blahp/pbs_status.py", line 564, in <module>
    sys.exit(main())
  File "/usr/libexec/blahp/pbs_status.py", line 531, in main
    'pbs_binpath': '/usr/bin'})
  File "/usr/libexec/blahp/blah.py", line 15, in __init__
    vfile = StringIO(u'[%s]\n%s' % (self.header, config))
UnicodeDecodeError: 'ascii' codec can't decode byte 0xb0 in position 3470: ordinal not in range(128)

10/23/17 11:59:07 164142 Traceback (most recent call last):
  File "/usr/libexec/blahp/pbs_status.py", line 564, in <module>
    sys.exit(main())
  File "/usr/libexec/blahp/pbs_status.py", line 531, in main
    'pbs_binpath': '/usr/bin'})
  File "/usr/libexec/blahp/blah.py", line 15, in __init__
    vfile = StringIO(u'[%s]\n%s' % (self.header, config))
UnicodeDecodeError: 'ascii' codec can't decode byte 0xb0 in position 3470: ordinal not in range(128)

10/23/17 12:00:07 164223 Traceback (most recent call last):
  File "/usr/libexec/blahp/pbs_status.py", line 564, in <module>
    sys.exit(main())
  File "/usr/libexec/blahp/pbs_status.py", line 531, in main
    'pbs_binpath': '/usr/bin'})
  File "/usr/libexec/blahp/blah.py", line 15, in __init__
    vfile = StringIO(u'[%s]\n%s' % (self.header, config))
UnicodeDecodeError: 'ascii' codec can't decode byte 0xb0 in position 3470: ordinal not in range(128)

10/23/17 12:01:07 164305 Traceback (most recent call last):
  File "/usr/libexec/blahp/pbs_status.py", line 564, in <module>
    sys.exit(main())
  File "/usr/libexec/blahp/pbs_status.py", line 531, in main
    'pbs_binpath': '/usr/bin'})
  File "/usr/libexec/blahp/blah.py", line 15, in __init__
    vfile = StringIO(u'[%s]\n%s' % (self.header, config))
UnicodeDecodeError: 'ascii' codec can't decode byte 0xb0 in position 3470: ordinal not in range(128)

10/23/17 12:02:07 164428 Traceback (most recent call last):
  File "/usr/libexec/blahp/pbs_status.py", line 564, in <module>
    sys.exit(main())
  File "/usr/libexec/blahp/pbs_status.py", line 531, in main
    'pbs_binpath': '/usr/bin'})
  File "/usr/libexec/blahp/blah.py", line 15, in __init__
    vfile = StringIO(u'[%s]\n%s' % (self.header, config))
UnicodeDecodeError: 'ascii' codec can't decode byte 0xb0 in position 3470: ordinal not in range(128)

10/23/17 12:02:58 164482 Traceback (most recent call last):
  File "/usr/libexec/blahp/pbs_status.py", line 564, in <module>
    sys.exit(main())
  File "/usr/libexec/blahp/pbs_status.py", line 531, in main
    'pbs_binpath': '/usr/bin'})
  File "/usr/libexec/blahp/blah.py", line 15, in __init__
    vfile = StringIO(u'[%s]\n%s' % (self.header, config))
UnicodeDecodeError: 'ascii' codec can't decode byte 0xb0 in position 3470: ordinal not in range(128)

10/23/17 12:03:07 164493 Traceback (most recent call last):
  File "/usr/libexec/blahp/pbs_status.py", line 564, in <module>
    sys.exit(main())
  File "/usr/libexec/blahp/pbs_status.py", line 531, in main
    'pbs_binpath': '/usr/bin'})
  File "/usr/libexec/blahp/blah.py", line 15, in __init__
    vfile = StringIO(u'[%s]\n%s' % (self.header, config))
UnicodeDecodeError: 'ascii' codec can't decode byte 0xb0 in position 3470: ordinal not in range(128)

10/23/17 12:03:58 164548 Traceback (most recent call last):
  File "/usr/libexec/blahp/pbs_status.py", line 564, in <module>
    sys.exit(main())
  File "/usr/libexec/blahp/pbs_status.py", line 531, in main
    'pbs_binpath': '/usr/bin'})
  File "/usr/libexec/blahp/blah.py", line 15, in __init__
    vfile = StringIO(u'[%s]\n%s' % (self.header, config))
UnicodeDecodeError: 'ascii' codec can't decode byte 0xb0 in position 3470: ordinal not in range(128)

10/23/17 12:04:58 164658 Traceback (most recent call last):
  File "/usr/libexec/blahp/pbs_status.py", line 564, in <module>
    sys.exit(main())
  File "/usr/libexec/blahp/pbs_status.py", line 531, in main
    'pbs_binpath': '/usr/bin'})
  File "/usr/libexec/blahp/blah.py", line 15, in __init__
    vfile = StringIO(u'[%s]\n%s' % (self.header, config))
UnicodeDecodeError: 'ascii' codec can't decode byte 0xb0 in position 3470: ordinal not in range(128)

10/23/17 12:05:58 164741 Traceback (most recent call last):
  File "/usr/libexec/blahp/pbs_status.py", line 564, in <module>
    sys.exit(main())
  File "/usr/libexec/blahp/pbs_status.py", line 531, in main
    'pbs_binpath': '/usr/bin'})
  File "/usr/libexec/blahp/blah.py", line 15, in __init__
    vfile = StringIO(u'[%s]\n%s' % (self.header, config))
UnicodeDecodeError: 'ascii' codec can't decode byte 0xb0 in position 3470: ordinal not in range(128)

10/23/17 12:06:58 164807 Traceback (most recent call last):
  File "/usr/libexec/blahp/pbs_status.py", line 564, in <module>
    sys.exit(main())
  File "/usr/libexec/blahp/pbs_status.py", line 531, in main
    'pbs_binpath': '/usr/bin'})
  File "/usr/libexec/blahp/blah.py", line 15, in __init__
    vfile = StringIO(u'[%s]\n%s' % (self.header, config))
UnicodeDecodeError: 'ascii' codec can't decode byte 0xb0 in position 3470: ordinal not in range(128)

10/23/17 12:11:41 164934 Traceback (most recent call last):
  File "/usr/libexec/blahp/pbs_status.py", line 564, in <module>
    sys.exit(main())
  File "/usr/libexec/blahp/pbs_status.py", line 531, in main
    'pbs_binpath': '/usr/bin'})
  File "/usr/libexec/blahp/blah.py", line 15, in __init__
    vfile = StringIO(u'[%s]\n%s' % (self.header, config))
UnicodeDecodeError: 'ascii' codec can't decode byte 0xb0 in position 3470: ordinal not in range(128)

